### PR TITLE
Support for alternative Entity Names and multiple DBs

### PR DESCRIPTION
**Pull request by master-lincoln**
I couldn't use the plugin because the lack of support for these 2 features.
It were just a few lines to add.

### CODE REVIEW

**Comment by lmcalpin** [comment]
getAnnotation(Entity.class).name() will be an empty string if you use @Entity without the name attribute.  We should default to the existing logic for users who do not use the name attribute.  

I'll go ahead and merge this in as is and patch it afterwards since it's a minor fix.

Thanks for the contribution.

**Comment by lmcalpin** [comment]
Doh. I guess I shouldn't have used the easy button merge option.  I think JPA.getJPAConfig must be a new API.  Can you confirm that you are using play from the mainline? I don't see this API in 1.2.3...

**Comment by master-lincoln** [comment]
Ohh...no I'm using the current git master branch. They included documentation for multi DB support even before the 1.2.3 release but looks like they did not yet include the code. I guess it'll be in the next version. Sorry I didn't notice that before

**Comment by lmcalpin** [comment]
I made a change to avoid calling the code if the JPA.getJPAContext() method isn't available, so that this will continue to work for users of Play! <= 1.2.3. Thanks!

**Pull request merged**
